### ISSUE TITLE
How to let nginx log the ssl key log file by changing nginx.conf file 

### ISSUE THREAD

**Issue by Karthikdasari0423** [nginx/nginx-quic-qns#4]
Hi  ,

My goal is capture the pcap file on my linux machine which is using nginx quic to connect and decrypt those packets using ssl key log file.but i am unable to find how to capture ssl key log file on nginx. Could someone please help me how to capture ssl key log file ?

Looking forward for you reply.

Thanks,
Kartheek.

**Comment by marten-seemann** [comment]
Not sure why I'm getting tagged here, I have nothing to do with this repo. @Karthikdasari0423, please don't just spam people with notifications.

**Comment by Karthikdasari0423** [comment]
Hi @marten-seemann ,

Thank you for replying back,

I have been using your 2 github repos of quic and those are great repos.
I thought you might have a idea on this and i tagged you here cause it think it might not be a good idea to raise a issue in any of your repos and ask this query.

Sorry for bothering you.

Thank you.
@Karthikdasari0423

**Comment by marten-seemann** [comment]
> I have been using your 2 github repos of quic and those are great repos.

Great to hear that :)

> Sorry for bothering you.

No worries! Sorry for my unfriendly reply earlier. Unfortunately, I can't help you with your issue.

**Comment by Karthikdasari0423** [comment]
okay,No problem.
Thank you @marten-seemann
