### ISSUE TITLE
Nginx - Too Large Request URI

### ISSUE THREAD

**Issue by Mani7998** [nginx/nginx-quic-qns#8]
When I am trying to save a large text of more than 10000 characters, Nginx says: "414 Request URI Too Large", even though the save method is PATCH. I have tried to increase the limit by using the below parameters but it's of no help:

        client_max_body_size 50M;
        client_header_buffer_size 64k;
        client_body_buffer_size 64k;

        # Header size increase
        proxy_buffers 16 64k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 64k;
        large_client_header_buffers 16 64k;
       
I tried with various values for the above parameters, but the maximum content allows me to be only 10000 characters. A few of the things I observed is, it allowing more than 10000 characters when there is no space involved in the content. 

Also, the behavior seems to be inconsistent when copying the content from word documents and other online editors. I have HTML-rich text in my content and that seems to be causing the issue here. We do not have any conflicting config or parameters where we are limiting the content length.

**Comment by thresheek** [comment]
Hi @Mani7998!

This seems to be related to general NGINX, and not nginx qns interop image.  We don't offer tech support for NGINX in general here - please use mailing lists for that https://nginx.org/en/support.html

Thank you!
